### ISSUE TITLE
problem with running tradis pipeline multiple

### ISSUE THREAD

**Issue by gaworj** [quadram-institute-bioscience/QuaTradis#30]
Hello,

When I try to run following command using quatradis:

tradis pipeline multiple -v -n 12 -o quatradis_out fastqs_filtered_sizecut_all.txt genome.fa

this error appears:
Traceback (most recent call last):
  File "/home/jang/anaconda3/envs/mamba/envs/albatradis/bin/tradis", line 293, in <module>
    main()
  File "/home/jang/anaconda3/envs/mamba/envs/albatradis/bin/tradis", line 285, in main
    args.func(args)
  File "/home/jang/anaconda3/envs/mamba/envs/albatradis/bin/tradis", line 202, in run_multiple_pipeline
    tradis.run_multi_tradis(args.fastqs, args.reference,
  File "/home/jang/anaconda3/envs/mamba/envs/albatradis/lib/python3.9/site-packages/quatradis/tradis.py", line 142, in run_multi_tradis
    pipeline = find_pipeline_file()
  File "/home/jang/anaconda3/envs/mamba/envs/albatradis/lib/python3.9/site-packages/quatradis/tradis.py", line 101, in find_pipeline_file
    if os.path.exists(exe_path):
  File "/home/jang/anaconda3/envs/mamba/envs/albatradis/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

What I'm doing wrong?

The same input files work smoothly in bacteria_tradis.

Bests,
Jan

**Comment by sbastkowski** [comment]
Hi Jan, we are aware of this issue and are in the process of fixing it. In the meantime we strongly encouraged to use docker for running the multiple pipeline. I will update you asap on the progress.
